### ISSUE TITLE
No recent releases

### ISSUE THREAD

**Issue by rkeene** [Terradue/cloud-bursting4one#1]
There haven't been any releases since v0.1.8 in 2015.  The commit messages include the words "merge " and "release" and "branch", but there is no release branch and, again, no new releases.  Is this project still alive ?  Are there any plans for a release ?

**Comment by rkeene** [comment]
Just checking in to see if this project is dead.

**Comment by crossi202** [comment]
Hi @rkeene,
this git repository wasn't really updated. I've just aligned it with another internal one.
We do not use release branches but tags, so you can check the most recent release code by selecting the proper git tag.
Cheers,
Cesare
